version: "3.8"
services:
  app:
    build: .

    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: postiks
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
  redis:
    image: redis
  celery:
    build: .
    command: celery -A postiks worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A postiks beat -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
